"""Cost ledger (2026-10-06; the user: "only count our costs starting from Microsoft Azure and also from today with Jev.
All of the costs that are Fireworks, let's leave them so we don't mix things"). Azure models (GPT-6 Luna, Kimi K2.6,
DeepSeek V4 Flash) and Jev, from 2026-10-06, from our usage logs; Fireworks and Runpod are not counted here.
Writes ../COSTS.md.  usage: dspy_venv/bin/python analysis/costs.py   (run from lab_tool/)"""
import glob, json, os, re
L = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# USD per 1M tokens (the user, 2026-10-06): (input, cached input, cache write, output); None = no separate rate
PRICES = {
    "GPT-6 Luna, prompt < 250k tokens": (0.11, 0.011, 0.14, 0.55),
    "GPT-6 Luna, prompt >= 250k tokens": (0.20, 0.02, 0.25, 0.75),
    "Kimi K2.6 Thinking": (0.95, 0.16, None, 4.00),
    "DeepSeek V4 Flash": (0.19, 0.03, None, 0.51),
    "Jev (TypeSafe)": (0.042, None, None, 0.0),
}


def usd(price, i, c=0, w=0, o=0):
    """Azure's input count includes cached and cache-written tokens."""
    p = PRICES[price]
    return (max(0, i - c - w) * p[0] + c * (p[1] if p[1] is not None else p[0]) + w * (p[2] if p[2] is not None else p[0]) + o * p[3]) / 1e6


def luna_price(i):
    return "GPT-6 Luna, prompt >= 250k tokens" if i >= 250_000 else "GPT-6 Luna, prompt < 250k tokens"


def load(path):
    return [json.loads(l) for l in open(path)] if os.path.exists(path) else []


def rows():
    R = []
    def add(model, job, U, price):
        n = len(U); i = sum(u[0] for u in U); c = sum(u[1] for u in U); w = sum(u[2] for u in U); o = sum(u[3] for u in U)
        if n: R.append((model, job, n, i, c, w, o, sum(usd(price(u[0]) if callable(price) else price, *u) for u in U)))
    tags = {}
    for u in load(f"{L}/runs/luna_usage.jsonl"):
        tags.setdefault(u["tag"], []).append((u["input"], u.get("cached", 0), u.get("cache_write", 0), u["output"]))
    for tag, U in tags.items(): add("GPT-6 Luna", f"jev_judge: {tag}", U, luna_price)
    U = [(u["prompt"], u["cached"], u.get("cache_write", 0), u["completion"]) for f in glob.glob(f"{L}/runs/pilot/*-luna*.usage.jsonl") for u in load(f)]
    add("GPT-6 Luna", "LAB agent episodes (max effort)", U, luna_price)
    U = [(u["input"], u["cached"], u.get("cache_write", 0), u["output"]) for u in load(f"{L}/runs/kimi26_usage.jsonl")]
    add("Kimi K2.6 Thinking", "judge validation", U, "Kimi K2.6 Thinking")
    U = [(u["prompt"], u["cached"], u.get("cache_write", 0), u["completion"]) for f in glob.glob(f"{L}/runs/pilot/*-dsv4*.usage.jsonl") for u in load(f)]
    add("DeepSeek V4 Flash", "LAB agent episodes", U, "DeepSeek V4 Flash")
    # Jev: the first check run (before per-run logging) from its log; later runs from jev_usage.jsonl
    if os.path.exists(f"{L}/runs/jev_check.log"):
        m = re.findall(r"Jev calls (\d+), tokens in ([\d,]+)", open(f"{L}/runs/jev_check.log").read())
        if m: R.append(("Jev", "jev_judge: check, all recorded criteria (from its log)", int(m[-1][0]), int(m[-1][1].replace(",", "")), 0, 0, 0,
                        usd("Jev (TypeSafe)", int(m[-1][1].replace(",", "")))))
    for u in load(f"{L}/runs/jev_usage.jsonl"):
        R.append(("Jev", f"jev_judge: {u['job']}", u["calls"], u["input"], 0, 0, 0, usd("Jev (TypeSafe)", u["input"])))
    return R


if __name__ == "__main__":
    R = rows(); fmt = lambda x: "-" if x is None else f"${x:g}"
    out = ["# Cost ledger: Azure models + Jev (from 2026-10-06)", "",
           "Generated by `analysis/costs.py` from our usage logs (re-run it to update). Fireworks and Runpod costs are not",
           "counted here (the user: keep them apart). Azure's input count includes cached and cache-written tokens.", "",
           "## Prices (USD per 1M tokens)", "", "| model | input | cached input | cache write | output |", "|---|---|---|---|---|"]
    out += [f"| {k} | " + " | ".join(fmt(x) for x in v) + " |" for k, v in PRICES.items()]
    out += ["", "## Usage", "", "| model | job | calls | input | cached | cache write | output | USD |", "|---|---|---|---|---|---|---|---|"]
    tot = {}
    for m, job, n, i, c, w, o, d in R:
        out.append(f"| {m} | {job} | {n} | {i / 1e6:.1f}M | {c / 1e6:.1f}M | {w / 1e6:.2f}M | {o / 1e6:.2f}M | ${d:.2f} |"); tot[m] = tot.get(m, 0) + d
    out += ["", "| model | USD |", "|---|---|"] + [f"| {m} | ${d:.2f} |" for m, d in tot.items()] + [f"| **total** | **${sum(tot.values()):.2f}** |"]
    open(f"{L}/COSTS.md", "w").write("\n".join(out) + "\n"); print("\n".join(out[out.index("## Usage"):]))
