"""GPU cost per 1M tokens on our Runpod RTX 4090 pods (2026-10-06; the user: "record exactly the total time of 4090
running and then multiply it by cost (usually $0.70 / hour) and divide by the total qty of tokens passed").
Exact billed time and dollars per pod from Runpod's billing API (GET /v1/billing/pods, hourly buckets; the amount
includes disk), tokens from our logs (every Gemma call on that pod: input + output). Writes ../GPU_COSTS.md.
usage (from lab_tool/): dspy_venv/bin/python analysis/gpu_costs.py"""
import calendar, glob, json, os, subprocess, time
KEY = next(l.split("=", 1)[1].strip().strip('"\'') for l in open("/root/.env") if l.startswith("RUNPOD_API_KEY="))
RATE = 0.70  # the user's usual $/hour for a 4090
# pods of the LAB work today, what ran on them, and where their tokens are logged (all calls in these logs ran there)
PODS = {
    "gbf93fff46rix6": ("Gemma 4 E4B (vLLM): LAB agent episodes", ["runs/pilot/*-gemma-e4b.usage.jsonl"], None),
    "3prci9s24aa7wz": ("Gemma 4 26B-A4B (llama.cpp): LAB agent episodes", ["runs/pilot/*-gemma-26b.usage.jsonl"], None),
    "0l1w4j0egtvdts": ("Gemma 4 26B-A4B: pipeline v1-v3 (dev + test)", ["runs/pipeline_gemma_usage.jsonl"], (0, "2026-10-06T11:47:05Z")),
    "4pf0mwm2y3fpnn": ("Gemma 4 26B-A4B: pipeline v4-v5.1 (dev + test), v5 replays, reranker", ["runs/pipeline_gemma_usage.jsonl"], ("2026-10-06T11:47:05Z", None)),
    "l0eh7nqu4v6pw9": ("Gemma 4 26B-A4B from the EU-RO-1 volume: GPU comparison workload (GPU_COMPARE.md)", ["runs/gpu_compare/dedicated-eu-ro-1.jsonl"], None),
    "g3l04thzdztfae": ("CPU pod (2 vCPU): filled the EU-RO-1 network volume", [], None),
}


# busy time: the union of the [start, end] of every run that used the pod (end = when metrics.json was written,
# start = end - the run's wall-clock time): GPU time spent serving our calls, without setup, downloads and idle time
RUNS = {"gbf93fff46rix6": ["harvey-labs/results/pilot-*-gemma-e4b/metrics.json"],
        "3prci9s24aa7wz": ["harvey-labs/results/pilot-*-gemma-26b/metrics.json"],
        "0l1w4j0egtvdts": ["runs/pipe_dev_v*/pipe-gemma26-*/metrics.json", "harvey-labs/results/pipe-gemma26-*/metrics.json"],
        "4pf0mwm2y3fpnn": ["runs/pipe_devcmp_buggy/pipe-v[34]-gemma26-*/metrics.json",
                           "harvey-labs/results/pipe-v41-gemma26-*/metrics.json", "harvey-labs/results/pipe-v42-gemma26-*/metrics.json",
                           "harvey-labs/results/pipe-v43-gemma26-*/metrics.json", "harvey-labs/results/pipe-v5-gemma26-*/metrics.json",
                           "harvey-labs/results/pipe-v51-gemma26-*/metrics.json"]}


def busy_hours(pod, window):
    lo = ts(window[0]) if window and window[0] else 0; hi = ts(window[1]) if window and window[1] else 1e12
    iv = []
    for g in RUNS.get(pod, []):
        for f in glob.glob(g):
            end = os.path.getmtime(f); w = json.load(open(f)).get("wall_clock_seconds") or 0
            if lo <= end < hi: iv.append((end - w, end))
    iv.sort(); tot, cur = 0.0, None
    for a, b in iv:
        if cur and a <= cur[1]: cur = (cur[0], max(cur[1], b))
        else:
            if cur: tot += cur[1] - cur[0]
            cur = (a, b)
    if cur: tot += cur[1] - cur[0]
    return tot / 3600, len(iv)


def ts(x):
    return x if isinstance(x, (int, float)) else calendar.timegm(time.strptime(x, "%Y-%m-%dT%H:%M:%SZ"))


def billing():
    out = subprocess.run(["curl", "-s", "-H", f"Authorization: Bearer {KEY}",
                          "https://rest.runpod.io/v1/billing/pods?bucketSize=hour&startTime=2026-10-05T00:00:00Z&endTime=2026-10-31T00:00:00Z"],
                         capture_output=True, text=True).stdout
    b = {}
    for r in json.loads(out):
        x = b.setdefault(r["podId"], [0, 0.0]); x[0] += r["timeBilledMs"]; x[1] += r["amount"]
    return b


def tokens(globs, window):
    lo = ts(window[0]) if window and window[0] else 0; hi = ts(window[1]) if window and window[1] else 1e12
    n = calls = 0
    for g in globs:
        for f in glob.glob(g):
            for u in map(json.loads, open(f)):
                t = u.get("t")
                if window and t is not None and not (lo <= t < hi): continue
                n += u.get("input", u.get("prompt", 0)) + u.get("output", u.get("completion", 0)); calls += 1
    return n, calls


if __name__ == "__main__":
    B = billing(); rows = []; tot = [0, 0.0, 0, 0, 0.0]
    for pod, (what, globs, window) in PODS.items():
        ms, usd = B.get(pod, (0, 0.0)); n, calls = tokens(globs, window)
        h = ms / 3.6e6; bh, nr = busy_hours(pod, window); rows.append((pod, what, h, usd, h * RATE, n, calls, bh, nr))
        if ms: tot = [tot[0] + h, tot[1] + usd, tot[2] + n, tot[3] + calls, tot[4] + bh]  # the total: billed pods only
    L = ["# GPU cost per 1M tokens (Runpod RTX 4090)", "", "Generated by `analysis/gpu_costs.py`: billed time and dollars from Runpod's billing API (the amount",
         "includes disk), tokens = every Gemma call we logged on that pod (input + output). Kept apart from the Azure + Jev ledger.", "",
         "| pod | what ran | billed hours | billed USD | hours x $0.70 | tokens | calls | USD / 1M tokens (billed) | USD / 1M tokens ($0.70/h) | busy hours (runs) | USD / 1M tokens, busy time only ($0.70/h) |",
         "|---|---|---|---|---|---|---|---|---|---|---|"]
    for pod, what, h, usd, r, n, calls, bh, nr in rows:
        per = lambda x: f"${x / (n / 1e6):.3f}" if n else "-"
        L.append(f"| {pod} | {what} | {h:.3f} | ${usd:.2f} | ${r:.2f} | {n / 1e6:.2f}M | {calls} | {per(usd)} | {per(r)} | {bh:.3f} ({nr}) | {per(bh * RATE)} |")
    per = lambda x: f"${x / (tot[2] / 1e6):.3f}" if tot[2] else "-"
    L.append(f"| **all billed pods** | | **{tot[0]:.3f}** | **${tot[1]:.2f}** | **${tot[0] * RATE:.2f}** | **{tot[2] / 1e6:.2f}M** | {tot[3]} | **{per(tot[1])}** | **{per(tot[0] * RATE)}** | **{tot[4]:.3f}** | **{per(tot[4] * RATE)}** |")
    L += ["", "A pod with 0 billed hours is not in the billing API's window (or not billed yet) and is left out of the total.",
          "A pod also bills while it sets up (building llama.cpp, downloading the model, ~10 min) and while idle: the per-token",
          "cost falls as more work runs on one pod."]
    open("GPU_COSTS.md", "w").write("\n".join(L) + "\n"); print("\n".join(L))
