"""Dedicated 4090 pod (storage-optimized start) vs Runpod Serverless, same workload (2026-10-06; the user: "Make sure you
measure that serverless costs correctly. We want to compare them correctly with our dedicated pod with storage-optimized
start."). Both read Google's Gemma 4 26B-A4B QAT Q4_0 GGUF from one network volume (EU-RO-1) with the same image
(ghcr.io/ggml-org/llama.cpp:server-cuda-b11312) and flags; workload = pods/replay_workload.py (453 logged contract-review
prompts, 4 in flight). Billed seconds and dollars from Runpod's billing API when it has them (hourly buckets, delayed),
else from the measured times at the listed rate (marked "est."). Writes ../GPU_COMPARE.md.
usage (from lab_tool/): dspy_venv/bin/python analysis/gpu_compare.py"""
import collections, json, subprocess
KEY = next(l.split("=", 1)[1].strip().strip('"\'') for l in open("/root/.env") if l.startswith("RUNPOD_API_KEY="))
POD_RATE, SLS_RATE, VOL_GB, VOL_RATE = 0.74, 1.10, 20, 0.07  # $/h 4090 pod (secure), $/h 4090 serverless flex, volume GB, $/GB/month


def billing(kind, group):
    out = subprocess.run(["curl", "-s", "-H", f"Authorization: Bearer {KEY}",
                          f"https://rest.runpod.io/v1/billing/{kind}?bucketSize=hour&startTime=2026-10-06T00:00:00Z&endTime=2026-10-08T00:00:00Z"
                          + (f"&grouping={group}" if group else "")], capture_output=True, text=True).stdout
    b = collections.defaultdict(lambda: [0, 0.0])
    for r in json.loads(out or "[]"):
        k = r.get("podId") or r.get("endpointId"); b[k][0] += r.get("timeBilledMs", 0); b[k][1] += r.get("amount", 0.0)
    return b


if __name__ == "__main__":
    d = json.load(open("runs/gpu_compare/dedicated.json")); s = json.load(open("runs/gpu_compare/dedicated-eu-ro-1.summary.json"))
    tok = s["input_tokens"] + s["output_tokens"]; P = billing("pods", None); E = billing("endpoints", "endpointId")
    life = d["deleted_t"] - d["created_t"]; ms, usd = P.get(d["pod"], (0, 0.0))
    ded_usd, ded_note = (usd, f"billed {ms / 1000:.0f} s") if ms else (life / 3600 * POD_RATE, f"est.: {life:.0f} s x ${POD_RATE}/h")
    # serverless: billed = worker start (image from cache + container start) + model load + execution + idle timeout
    # (Runpod docs). Measured on our endpoint: image 16 s, model load to listening 25 s; execution = the same workload on
    # the same GPU type, engine and flags (the dedicated run); idle timeout 10 s.
    sls_s = 16 + 25 + s["wall_s"] + 10
    em, eu = E.get("j8sh1gaz0yc9ya", (0, 0.0))
    L = ["# Dedicated pod vs serverless (RTX 4090, Gemma 4 26B-A4B Q4_0, llama.cpp)", "",
         "Generated by `analysis/gpu_compare.py`. Workload: 453 logged contract-review prompts (4 dev tasks; from the abandoned fixed pipeline), 4 in flight,",
         f"{s['input_tokens']:,} input + {s['output_tokens']:,} output tokens = {tok / 1e6:.2f}M tokens. Same image, flags and model file (network volume, EU-RO-1).", "",
         "| setup | start to serving | workload | billed time | USD | USD / 1M tokens |", "|---|---|---|---|---|---|",
         f"| dedicated pod, model on the network volume | {d['ready_t'] - d['created_t']:.0f} s | {s['wall_s']:.0f} s, {s['errors']} errors | {ded_note} | ${ded_usd:.3f} | ${ded_usd / (tok / 1e6):.3f} |",
         f"| serverless flex worker (est.: our endpoint never served, see below) | 41 s (16 s image + 25 s model load, measured) | {s['wall_s']:.0f} s (same GPU, engine, flags) | est.: {sls_s:.0f} s x ${SLS_RATE}/h | ${sls_s / 3600 * SLS_RATE:.3f} | ${sls_s / 3600 * SLS_RATE / (tok / 1e6):.3f} |",
         "", f"Network volume ({VOL_GB} GB): ${VOL_GB * VOL_RATE:.2f} per month for either setup, on top.", "",
         "Per hour of serving: dedicated $0.74 whether busy or idle; serverless $1.10 only while a worker is up (start + work + 10 s",
         "idle). Serverless is cheaper only when the GPU would otherwise sit idle more than ~1/3 of the time (0.74 / 1.10 = 67% busy).",
         "A task of 100-270 such calls keeps the GPU busy for 3-8 minutes, so per task: dedicated ~$0.05-0.10 if the pod is already up; serverless",
         "~$0.07-0.16 including its ~40 s start, paid on every cold start.", "",
         "## Serverless attempt (2026-10-06, EU-RO-1, load-balancer endpoint j8sh1gaz0yc9ya, deleted)",
         "Two workers started and loaded the model (container start to `listening on 0.0.0.0:8080` in 25 s), but the load balancer",
         "never routed a request to them (every request through https://<id>.api.runpod.ai hung; 12 minutes of polling). The first",
         "worker was exited by Runpod after ~9.5 min; the second was stopped by us. Likely cause: the load balancer's health check",
         "never passed (HEALTH_CHECK_PATH=/health on port 8080 was set as documented), not the model or GPU. Not resolved; the cost",
         "of the failed attempt is " + (f"${eu:.3f} ({em / 1000:.0f} s billed)." if em else "not in the billing API yet (~22 worker-minutes at $1.10/h, ~$0.40).")]
    open("GPU_COMPARE.md", "w").write("\n".join(L) + "\n"); print("\n".join(L))
